/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Binner: typeof import('./src/components/common/Binner.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    Carousel: typeof import('./src/components/common/Carousel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Gauge: typeof import('./src/components/charts/Gauge.vue')['default']
    GfktGague: typeof import('./src/components/gfkt/GfktGague.vue')['default']
    GfktInfo: typeof import('./src/components/gfkt/GfktInfo.vue')['default']
    Granary3d: typeof import('./src/components/Granary3d.vue')['default']
    HouseInfo: typeof import('./src/components/HouseInfo.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    MailAuth: typeof import('./src/components/Login/MailAuth.vue')['default']
    NhlGague: typeof import('./src/components/nhl/NhlGague.vue')['default']
    NhlGague2: typeof import('./src/components/nhl/NhlGague2.vue')['default']
    NhlInfo: typeof import('./src/components/nhl/NhlInfo.vue')['default']
    PageFrame: typeof import('./src/components/common/PageFrame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserNamePasswordAuth: typeof import('./src/components/Login/UserNamePasswordAuth.vue')['default']
  }
}
