
spring.application.name=demo
spring.profiles.active=dev
server.port=8080

#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

#logging.file.name=myapp.log

#staticRootDir=/Users/dadigua/Pictures/
#staticPrefix=img/

staticRootDir=d:\\minglun\\
staticPrefix=static/

#staticRootDir_line=d:\\minglun\\line\\
#staticPrefix_line=line/
#
#staticRootDir_alarm=d:\\minglun\\alarm\\
#staticPrefix_alarm=alarm/
#
#staticRootDir_threeD=d:\\minglun\\threeD\\
#staticPrefix_threeD=threeD/

