
spring.application.name=demo
spring.profiles.active=dev
server.port=8080


#staticRootDir=/Users/dadigua/Pictures/
#staticPrefix=img/

staticRootDir=d:\\minglun\\
staticPrefix=static/


guestToken=guest-token-123456
guest.username=guest


czh.mqtt.server=127.0.0.1:1883
czh.mqtt.userName=admin
czh.mqtt.password=123456


